#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChuyenBay
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChuyenBay")]
	public partial class QuanLyChuyenBayDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFlight(Flight instance);
    partial void UpdateFlight(Flight instance);
    partial void DeleteFlight(Flight instance);
    partial void InsertPassenger(Passenger instance);
    partial void UpdatePassenger(Passenger instance);
    partial void DeletePassenger(Passenger instance);
    partial void InsertTicket_Passenger(Ticket_Passenger instance);
    partial void UpdateTicket_Passenger(Ticket_Passenger instance);
    partial void DeleteTicket_Passenger(Ticket_Passenger instance);
    partial void InsertTicket(Ticket instance);
    partial void UpdateTicket(Ticket instance);
    partial void DeleteTicket(Ticket instance);
    partial void InsertUser(User instance);
    partial void UpdateUser(User instance);
    partial void DeleteUser(User instance);
    #endregion
		
		public QuanLyChuyenBayDataContext() : 
				base(global::QuanLyChuyenBay.Properties.Settings.Default.QuanLyChuyenBayConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChuyenBayDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChuyenBayDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChuyenBayDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyChuyenBayDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Flight> Flights
		{
			get
			{
				return this.GetTable<Flight>();
			}
		}
		
		public System.Data.Linq.Table<Passenger> Passengers
		{
			get
			{
				return this.GetTable<Passenger>();
			}
		}
		
		public System.Data.Linq.Table<Ticket_Passenger> Ticket_Passengers
		{
			get
			{
				return this.GetTable<Ticket_Passenger>();
			}
		}
		
		public System.Data.Linq.Table<Ticket> Tickets
		{
			get
			{
				return this.GetTable<Ticket>();
			}
		}
		
		public System.Data.Linq.Table<User> Users
		{
			get
			{
				return this.GetTable<User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Flights")]
	public partial class Flight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Flight_Number;
		
		private string _Arrival_City;
		
		private string _Departure_City;
		
		private System.Nullable<System.DateTime> _Arrival_Time;
		
		private System.Nullable<System.DateTime> _Departure_Time;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private string _UpdatedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnFlight_NumberChanging(string value);
    partial void OnFlight_NumberChanged();
    partial void OnArrival_CityChanging(string value);
    partial void OnArrival_CityChanged();
    partial void OnDeparture_CityChanging(string value);
    partial void OnDeparture_CityChanged();
    partial void OnArrival_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnArrival_TimeChanged();
    partial void OnDeparture_TimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDeparture_TimeChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    #endregion
		
		public Flight()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flight_Number", DbType="NVarChar(50)")]
		public string Flight_Number
		{
			get
			{
				return this._Flight_Number;
			}
			set
			{
				if ((this._Flight_Number != value))
				{
					this.OnFlight_NumberChanging(value);
					this.SendPropertyChanging();
					this._Flight_Number = value;
					this.SendPropertyChanged("Flight_Number");
					this.OnFlight_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrival_City", DbType="NVarChar(100)")]
		public string Arrival_City
		{
			get
			{
				return this._Arrival_City;
			}
			set
			{
				if ((this._Arrival_City != value))
				{
					this.OnArrival_CityChanging(value);
					this.SendPropertyChanging();
					this._Arrival_City = value;
					this.SendPropertyChanged("Arrival_City");
					this.OnArrival_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure_City", DbType="NVarChar(100)")]
		public string Departure_City
		{
			get
			{
				return this._Departure_City;
			}
			set
			{
				if ((this._Departure_City != value))
				{
					this.OnDeparture_CityChanging(value);
					this.SendPropertyChanging();
					this._Departure_City = value;
					this.SendPropertyChanged("Departure_City");
					this.OnDeparture_CityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Arrival_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Arrival_Time
		{
			get
			{
				return this._Arrival_Time;
			}
			set
			{
				if ((this._Arrival_Time != value))
				{
					this.OnArrival_TimeChanging(value);
					this.SendPropertyChanging();
					this._Arrival_Time = value;
					this.SendPropertyChanged("Arrival_Time");
					this.OnArrival_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Departure_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Departure_Time
		{
			get
			{
				return this._Departure_Time;
			}
			set
			{
				if ((this._Departure_Time != value))
				{
					this.OnDeparture_TimeChanging(value);
					this.SendPropertyChanging();
					this._Departure_Time = value;
					this.SendPropertyChanged("Departure_Time");
					this.OnDeparture_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Passengers")]
	public partial class Passenger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Pasenger_Passport_No;
		
		private System.Nullable<System.DateTime> _Birth_Day;
		
		private string _Passenger_Name;
		
		private string _Passenger_Address;
		
		private System.Nullable<bool> _Passenger_Sex;
		
		private string _Passenger_Phone;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private string _UpdatedBy;
		
		private EntitySet<Ticket_Passenger> _Ticket_Passengers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnPasenger_Passport_NoChanging(string value);
    partial void OnPasenger_Passport_NoChanged();
    partial void OnBirth_DayChanging(System.Nullable<System.DateTime> value);
    partial void OnBirth_DayChanged();
    partial void OnPassenger_NameChanging(string value);
    partial void OnPassenger_NameChanged();
    partial void OnPassenger_AddressChanging(string value);
    partial void OnPassenger_AddressChanged();
    partial void OnPassenger_SexChanging(System.Nullable<bool> value);
    partial void OnPassenger_SexChanged();
    partial void OnPassenger_PhoneChanging(string value);
    partial void OnPassenger_PhoneChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    #endregion
		
		public Passenger()
		{
			this._Ticket_Passengers = new EntitySet<Ticket_Passenger>(new Action<Ticket_Passenger>(this.attach_Ticket_Passengers), new Action<Ticket_Passenger>(this.detach_Ticket_Passengers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasenger_Passport_No", DbType="NVarChar(50)")]
		public string Pasenger_Passport_No
		{
			get
			{
				return this._Pasenger_Passport_No;
			}
			set
			{
				if ((this._Pasenger_Passport_No != value))
				{
					this.OnPasenger_Passport_NoChanging(value);
					this.SendPropertyChanging();
					this._Pasenger_Passport_No = value;
					this.SendPropertyChanged("Pasenger_Passport_No");
					this.OnPasenger_Passport_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birth_Day", DbType="DateTime")]
		public System.Nullable<System.DateTime> Birth_Day
		{
			get
			{
				return this._Birth_Day;
			}
			set
			{
				if ((this._Birth_Day != value))
				{
					this.OnBirth_DayChanging(value);
					this.SendPropertyChanging();
					this._Birth_Day = value;
					this.SendPropertyChanged("Birth_Day");
					this.OnBirth_DayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passenger_Name", DbType="NVarChar(100)")]
		public string Passenger_Name
		{
			get
			{
				return this._Passenger_Name;
			}
			set
			{
				if ((this._Passenger_Name != value))
				{
					this.OnPassenger_NameChanging(value);
					this.SendPropertyChanging();
					this._Passenger_Name = value;
					this.SendPropertyChanged("Passenger_Name");
					this.OnPassenger_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passenger_Address", DbType="NVarChar(100)")]
		public string Passenger_Address
		{
			get
			{
				return this._Passenger_Address;
			}
			set
			{
				if ((this._Passenger_Address != value))
				{
					this.OnPassenger_AddressChanging(value);
					this.SendPropertyChanging();
					this._Passenger_Address = value;
					this.SendPropertyChanged("Passenger_Address");
					this.OnPassenger_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passenger_Sex", DbType="Bit")]
		public System.Nullable<bool> Passenger_Sex
		{
			get
			{
				return this._Passenger_Sex;
			}
			set
			{
				if ((this._Passenger_Sex != value))
				{
					this.OnPassenger_SexChanging(value);
					this.SendPropertyChanging();
					this._Passenger_Sex = value;
					this.SendPropertyChanged("Passenger_Sex");
					this.OnPassenger_SexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Passenger_Phone", DbType="NVarChar(50)")]
		public string Passenger_Phone
		{
			get
			{
				return this._Passenger_Phone;
			}
			set
			{
				if ((this._Passenger_Phone != value))
				{
					this.OnPassenger_PhoneChanging(value);
					this.SendPropertyChanging();
					this._Passenger_Phone = value;
					this.SendPropertyChanged("Passenger_Phone");
					this.OnPassenger_PhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Passenger_Ticket_Passenger", Storage="_Ticket_Passengers", ThisKey="Id", OtherKey="Pasenger_Id")]
		public EntitySet<Ticket_Passenger> Ticket_Passengers
		{
			get
			{
				return this._Ticket_Passengers;
			}
			set
			{
				this._Ticket_Passengers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ticket_Passengers(Ticket_Passenger entity)
		{
			this.SendPropertyChanging();
			entity.Passenger = this;
		}
		
		private void detach_Ticket_Passengers(Ticket_Passenger entity)
		{
			this.SendPropertyChanging();
			entity.Passenger = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ticket_Passengers")]
	public partial class Ticket_Passenger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private System.Nullable<System.DateTime> _Return_Date;
		
		private System.Nullable<System.DateTime> _Reserver_Date;
		
		private System.Guid _Pasenger_Id;
		
		private System.Guid _Ticket_Id;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private string _UpdatedBy;
		
		private EntityRef<Passenger> _Passenger;
		
		private EntityRef<Ticket> _Ticket;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnReturn_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReturn_DateChanged();
    partial void OnReserver_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnReserver_DateChanged();
    partial void OnPasenger_IdChanging(System.Guid value);
    partial void OnPasenger_IdChanged();
    partial void OnTicket_IdChanging(System.Guid value);
    partial void OnTicket_IdChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    #endregion
		
		public Ticket_Passenger()
		{
			this._Passenger = default(EntityRef<Passenger>);
			this._Ticket = default(EntityRef<Ticket>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Return_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Return_Date
		{
			get
			{
				return this._Return_Date;
			}
			set
			{
				if ((this._Return_Date != value))
				{
					this.OnReturn_DateChanging(value);
					this.SendPropertyChanging();
					this._Return_Date = value;
					this.SendPropertyChanged("Return_Date");
					this.OnReturn_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reserver_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Reserver_Date
		{
			get
			{
				return this._Reserver_Date;
			}
			set
			{
				if ((this._Reserver_Date != value))
				{
					this.OnReserver_DateChanging(value);
					this.SendPropertyChanging();
					this._Reserver_Date = value;
					this.SendPropertyChanged("Reserver_Date");
					this.OnReserver_DateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pasenger_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Pasenger_Id
		{
			get
			{
				return this._Pasenger_Id;
			}
			set
			{
				if ((this._Pasenger_Id != value))
				{
					if (this._Passenger.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPasenger_IdChanging(value);
					this.SendPropertyChanging();
					this._Pasenger_Id = value;
					this.SendPropertyChanged("Pasenger_Id");
					this.OnPasenger_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Ticket_Id
		{
			get
			{
				return this._Ticket_Id;
			}
			set
			{
				if ((this._Ticket_Id != value))
				{
					if (this._Ticket.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTicket_IdChanging(value);
					this.SendPropertyChanging();
					this._Ticket_Id = value;
					this.SendPropertyChanged("Ticket_Id");
					this.OnTicket_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Passenger_Ticket_Passenger", Storage="_Passenger", ThisKey="Pasenger_Id", OtherKey="Id", IsForeignKey=true)]
		public Passenger Passenger
		{
			get
			{
				return this._Passenger.Entity;
			}
			set
			{
				Passenger previousValue = this._Passenger.Entity;
				if (((previousValue != value) 
							|| (this._Passenger.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Passenger.Entity = null;
						previousValue.Ticket_Passengers.Remove(this);
					}
					this._Passenger.Entity = value;
					if ((value != null))
					{
						value.Ticket_Passengers.Add(this);
						this._Pasenger_Id = value.Id;
					}
					else
					{
						this._Pasenger_Id = default(System.Guid);
					}
					this.SendPropertyChanged("Passenger");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ticket_Ticket_Passenger", Storage="_Ticket", ThisKey="Ticket_Id", OtherKey="Id", IsForeignKey=true)]
		public Ticket Ticket
		{
			get
			{
				return this._Ticket.Entity;
			}
			set
			{
				Ticket previousValue = this._Ticket.Entity;
				if (((previousValue != value) 
							|| (this._Ticket.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ticket.Entity = null;
						previousValue.Ticket_Passengers.Remove(this);
					}
					this._Ticket.Entity = value;
					if ((value != null))
					{
						value.Ticket_Passengers.Add(this);
						this._Ticket_Id = value.Id;
					}
					else
					{
						this._Ticket_Id = default(System.Guid);
					}
					this.SendPropertyChanged("Ticket");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tickets")]
	public partial class Ticket : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _Ticket_Number;
		
		private string _Ticket_Class;
		
		private System.Nullable<int> _Seat_Number;
		
		private string _Ticket_Price;
		
		private string _Fight_Number;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private string _UpdatedBy;
		
		private EntitySet<Ticket_Passenger> _Ticket_Passengers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnTicket_NumberChanging(string value);
    partial void OnTicket_NumberChanged();
    partial void OnTicket_ClassChanging(string value);
    partial void OnTicket_ClassChanged();
    partial void OnSeat_NumberChanging(System.Nullable<int> value);
    partial void OnSeat_NumberChanged();
    partial void OnTicket_PriceChanging(string value);
    partial void OnTicket_PriceChanged();
    partial void OnFight_NumberChanging(string value);
    partial void OnFight_NumberChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    #endregion
		
		public Ticket()
		{
			this._Ticket_Passengers = new EntitySet<Ticket_Passenger>(new Action<Ticket_Passenger>(this.attach_Ticket_Passengers), new Action<Ticket_Passenger>(this.detach_Ticket_Passengers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_Number", DbType="NVarChar(100)")]
		public string Ticket_Number
		{
			get
			{
				return this._Ticket_Number;
			}
			set
			{
				if ((this._Ticket_Number != value))
				{
					this.OnTicket_NumberChanging(value);
					this.SendPropertyChanging();
					this._Ticket_Number = value;
					this.SendPropertyChanged("Ticket_Number");
					this.OnTicket_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_Class", DbType="NVarChar(100)")]
		public string Ticket_Class
		{
			get
			{
				return this._Ticket_Class;
			}
			set
			{
				if ((this._Ticket_Class != value))
				{
					this.OnTicket_ClassChanging(value);
					this.SendPropertyChanging();
					this._Ticket_Class = value;
					this.SendPropertyChanged("Ticket_Class");
					this.OnTicket_ClassChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat_Number", DbType="Int")]
		public System.Nullable<int> Seat_Number
		{
			get
			{
				return this._Seat_Number;
			}
			set
			{
				if ((this._Seat_Number != value))
				{
					this.OnSeat_NumberChanging(value);
					this.SendPropertyChanging();
					this._Seat_Number = value;
					this.SendPropertyChanged("Seat_Number");
					this.OnSeat_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket_Price", DbType="NChar(10)")]
		public string Ticket_Price
		{
			get
			{
				return this._Ticket_Price;
			}
			set
			{
				if ((this._Ticket_Price != value))
				{
					this.OnTicket_PriceChanging(value);
					this.SendPropertyChanging();
					this._Ticket_Price = value;
					this.SendPropertyChanged("Ticket_Price");
					this.OnTicket_PriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fight_Number", DbType="NChar(10)")]
		public string Fight_Number
		{
			get
			{
				return this._Fight_Number;
			}
			set
			{
				if ((this._Fight_Number != value))
				{
					this.OnFight_NumberChanging(value);
					this.SendPropertyChanging();
					this._Fight_Number = value;
					this.SendPropertyChanged("Fight_Number");
					this.OnFight_NumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ticket_Ticket_Passenger", Storage="_Ticket_Passengers", ThisKey="Id", OtherKey="Ticket_Id")]
		public EntitySet<Ticket_Passenger> Ticket_Passengers
		{
			get
			{
				return this._Ticket_Passengers;
			}
			set
			{
				this._Ticket_Passengers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ticket_Passengers(Ticket_Passenger entity)
		{
			this.SendPropertyChanging();
			entity.Ticket = this;
		}
		
		private void detach_Ticket_Passengers(Ticket_Passenger entity)
		{
			this.SendPropertyChanging();
			entity.Ticket = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[User]")]
	public partial class User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _Id;
		
		private string _User_Name;
		
		private string _Pass_Word;
		
		private System.Nullable<System.DateTime> _Created;
		
		private string _CreatedBy;
		
		private System.Nullable<System.DateTime> _Updated;
		
		private string _UpdatedBy;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(System.Guid value);
    partial void OnIdChanged();
    partial void OnUser_NameChanging(string value);
    partial void OnUser_NameChanged();
    partial void OnPass_WordChanging(string value);
    partial void OnPass_WordChanged();
    partial void OnCreatedChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedChanged();
    partial void OnCreatedByChanging(string value);
    partial void OnCreatedByChanged();
    partial void OnUpdatedChanging(System.Nullable<System.DateTime> value);
    partial void OnUpdatedChanged();
    partial void OnUpdatedByChanging(string value);
    partial void OnUpdatedByChanged();
    #endregion
		
		public User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(50)")]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this.OnUser_NameChanging(value);
					this.SendPropertyChanging();
					this._User_Name = value;
					this.SendPropertyChanged("User_Name");
					this.OnUser_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pass_Word", DbType="NVarChar(50)")]
		public string Pass_Word
		{
			get
			{
				return this._Pass_Word;
			}
			set
			{
				if ((this._Pass_Word != value))
				{
					this.OnPass_WordChanging(value);
					this.SendPropertyChanging();
					this._Pass_Word = value;
					this.SendPropertyChanged("Pass_Word");
					this.OnPass_WordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime")]
		public System.Nullable<System.DateTime> Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedBy", DbType="NVarChar(50)")]
		public string CreatedBy
		{
			get
			{
				return this._CreatedBy;
			}
			set
			{
				if ((this._CreatedBy != value))
				{
					this.OnCreatedByChanging(value);
					this.SendPropertyChanging();
					this._CreatedBy = value;
					this.SendPropertyChanged("CreatedBy");
					this.OnCreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updated", DbType="DateTime")]
		public System.Nullable<System.DateTime> Updated
		{
			get
			{
				return this._Updated;
			}
			set
			{
				if ((this._Updated != value))
				{
					this.OnUpdatedChanging(value);
					this.SendPropertyChanging();
					this._Updated = value;
					this.SendPropertyChanged("Updated");
					this.OnUpdatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpdatedBy", DbType="NVarChar(50)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this.OnUpdatedByChanging(value);
					this.SendPropertyChanging();
					this._UpdatedBy = value;
					this.SendPropertyChanged("UpdatedBy");
					this.OnUpdatedByChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
